require_relative '../../pages_objects/pages/home_page'
require_relative '../../pages_objects/pages/advanced_search_page'
require_relative '../../pages_objects/pages/golf_equipment_page'
require_relative '../../pages_objects/pages/login_page'
require_relative '../../pages_objects/pages/category_community_page'